# Get comment by Id

GET http://localhost:3000/api/comments/552618b5-b807-4e51-9df5-9a5234389817 HTTP/1.1

###

# Delete a comment by id

DELETE http://localhost:3000/api/comments/3ee2cc3b-81cc-4789-bb50-d20b73ec2c34 HTTP/1.1

###
