# Create a new user
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "keks5@notfound.local",
  "name": "Keks",
  "avatar": "keks.png",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3001/api/auth/677e53ed7baca31a45997160 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:3001/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzdlNTNlZDdiYWNhMzFhNDU5OTcxNjAiLCJlbWFpbCI6Imtla3NAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsInRva2VuSWQiOiJmMjAxMzI3Ni0zNzUwLTRkMjctOGRmYy0xZmZlNDRjYTYwN2EiLCJpYXQiOjE3Mzc2Mzk3NTYsImV4cCI6MTc0MDIzMTc1Nn0.XtcoHlFrGTwyY4rcuDPy_UQjHMYnxoOV-sNIXyNDOZI

###
